typography_spectrum: 0.11135418131016195
color:
  brandStrength: 0.5546995478216559
  lightness: 0.04626260534860194
  saturation: 0.029105359222739935
  rhythmicContrast: 0.6588896161410958
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.12170375534333289
author:
  email: info@truehealthcenters.net
  url: www.truehealthcenters.net
  name: Joseph Ibe
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5985935b-7f79-462b-9b6f-58c7435117ac.jpg
name: True Health Centers
title: health solutions found here
description: health solutions found here
