typography_spectrum: 0.3689070870168507
color:
  brandStrength: 0.3760737089905888
  lightness: 0.6096183268819004
  saturation: 0.2614543105009943
  rhythmicContrast: 0.0046907695941627026
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
layout_spectrum: 0.6268691963050514
author:
  email: info@truehealthcenters.net
  url: www.truehealthcenters.net
  name: '407 N. San Mateo Drive San Mateo, CA 94401 | 650-740-7943'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5985935b-7f79-462b-9b6f-58c7435117ac.jpg
name: True Health Centers
navigation:
  - name: Blair Upper Cervical Chiropractic
    url: www.blairchiropractic.com
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a651b01b-1077-4151-8c30-3f9e5c85b4da.jpg
title: health solutions found here
description: an upper cervical chiropractic clinic
