typography_spectrum: 0.46439463226124644
color:
  brandStrength: 0.9292113063856959
  lightness: 0.5896644291933626
  saturation: 0.8370655470062047
  rhythmicContrast: 0.19881988083943725
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
layout_spectrum: 0.1812858316116035
author:
  email: info@truehealthcenters.net
  url: www.truehealthcenters.net
  name: '407 N. San Mateo Drive San Mateo, CA 94401 | 650-740-7943'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5985935b-7f79-462b-9b6f-58c7435117ac.jpg
name: True Health Centers
navigation:
  - name: Blair Upper Cervical Chiropractic
    url: www.blairchiropractic.com
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a651b01b-1077-4151-8c30-3f9e5c85b4da.jpg
title: health solutions found here
description: an upper cervical chiropractic clinic
